"""Interactively inspect one existing Layer 2 product embedding view."""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Iterable

from evaluator.agent_factory import build_evaluator_agent
from product_embeddings.layer2 import (
    LAYER2_VIEWS,
    Layer2EmbeddingIndex,
    Layer2EmbeddingMatch,
    build_layer2_view_text,
)


DEFAULT_CATALOG = Path("data/catalog.jsonl")
DEFAULT_ARTIFACT_DIR = Path("data/derived/product_embeddings_jina")
DEFAULT_MODEL_DIRS = (
    Path("model/jina-embeddings-v5-text-nano"),
    Path("models/jina-embeddings-v5-text-nano"),
)
TOP_K = 10

# These are the only semantic product views currently generated by Layer 2.
VIEW_OPTIONS = (
    ("category", "categories"),
    ("title", "title"),
    ("features", "features"),
    ("description", "description"),
)
VIEW_BY_NAME = {
    name: view
    for name, view in VIEW_OPTIONS
}
VIEW_BY_NAME.update(
    {
        "categories": "categories",
        "feature": "features",
        "descriptions": "description",
    }
)


@dataclass(frozen=True)
class SemanticSearchContext:
    retriever: Any
    index: Layer2EmbeddingIndex
    model_id: str
    dimension: int


def _embedding_model_override(explicit: str | None) -> str | None:
    if explicit and explicit.strip():
        return explicit.strip()
    configured = os.environ.get("SHOPPING_EMBEDDING_MODEL", "").strip()
    if configured:
        return configured
    for path in DEFAULT_MODEL_DIRS:
        if path.is_dir():
            return path.as_posix()
    return None


def load_search_context(
    catalog_path: str | Path = DEFAULT_CATALOG,
    artifact_dir: str | Path = DEFAULT_ARTIFACT_DIR,
    *,
    embedding_model: str | None = None,
) -> SemanticSearchContext:
    """Load the current Agent retriever and its existing Layer 2 index."""

    artifact = Path(artifact_dir)
    if not artifact.is_dir():
        raise RuntimeError(f"Layer 2 artifact directory is unavailable: {artifact}")

    agent = build_evaluator_agent(
        catalog_path,
        layer2_artifact_dir=artifact,
        embedding_model=_embedding_model_override(embedding_model),
    )
    retriever = agent.retriever
    index = retriever.layer2_index
    if index is None:
        raise RuntimeError(f"Layer 2 index could not be loaded from {artifact}")
    if not retriever.dense_available:
        reason = getattr(retriever, "layer2_compatibility_error", None)
        raise RuntimeError(reason or "Layer 2 semantic retrieval is unavailable")

    query_encoder = retriever.query_encoder
    model_id = str(
        getattr(
            query_encoder,
            "model_id",
            index.manifest.get("embedding_model", index.manifest.get("model", "")),
        )
    )
    if model_id.casefold() == "hashing-fallback-v1":
        raise RuntimeError("hashing-fallback-v1 is not allowed for semantic search")
    return SemanticSearchContext(
        retriever=retriever,
        index=index,
        model_id=model_id,
        dimension=index.dimension,
    )


def view_weights(selected_view: str) -> dict[str, float]:
    """Return Layer 2 weights that activate only one existing view."""

    if selected_view not in LAYER2_VIEWS:
        raise ValueError(f"unknown Layer 2 view: {selected_view}")
    return {
        view: 1.0 if view == selected_view else 0.0
        for view in LAYER2_VIEWS
    }


def search_view(
    context: SemanticSearchContext,
    selected_view: str,
    query: str,
    *,
    top_k: int = TOP_K,
) -> list[Layer2EmbeddingMatch]:
    """Encode and search using only the selected existing Layer 2 view."""

    if top_k < 1:
        raise ValueError("top_k must be positive")
    query_embedding = context.retriever._query_embedding(
        query,
        context.dimension,
    )
    if query_embedding is None:
        raise RuntimeError(
            "the current query encoder did not return a valid Layer 2 vector"
        )
    return context.index.search(
        query_embedding,
        top_k=top_k,
        weights=view_weights(selected_view),
    )


def product_view_text(
    context: SemanticSearchContext,
    match: Layer2EmbeddingMatch,
    selected_view: str,
) -> str:
    product = context.retriever.product_by_asin.get(match.parent_asin)
    if product is None:
        return ""
    return build_layer2_view_text(product.raw, selected_view)


def print_results(
    context: SemanticSearchContext,
    selected_view: str,
    matches: Iterable[Layer2EmbeddingMatch],
    *,
    output_fn: Callable[[str], None] = print,
) -> None:
    rows = list(matches)
    if not rows:
        output_fn("No products were returned.")
        return
    output_fn(
        f"#  product ASIN          similarity    {selected_view} view text"
    )
    for rank, match in enumerate(rows, 1):
        text = product_view_text(context, match, selected_view)
        text = " ".join(text.split())
        if len(text) > 100:
            text = text[:97] + "..."
        output_fn(
            f"{rank:>2}  {match.parent_asin:<20} "
            f"{match.score:>10.4f}    {text or '-'}"
        )


def _parse_view_choice(raw: str) -> str | None:
    normalized = raw.strip().casefold()
    if normalized in VIEW_BY_NAME:
        return VIEW_BY_NAME[normalized]
    try:
        index = int(normalized)
    except ValueError:
        return None
    if 1 <= index <= len(VIEW_OPTIONS):
        return VIEW_OPTIONS[index - 1][1]
    return None


def _choose_view(
    input_fn: Callable[[str], str],
    output_fn: Callable[[str], None],
) -> str | None:
    output_fn("Select semantic attribute/view:")
    for index, (label, _view) in enumerate(VIEW_OPTIONS, 1):
        output_fn(f"{index}. {label}")
    while True:
        try:
            raw = input_fn("> ")
        except (EOFError, KeyboardInterrupt):
            output_fn("")
            return None
        if raw.strip().casefold() == "q":
            return None
        selected = _parse_view_choice(raw)
        if selected is not None:
            return selected
        output_fn("Choose 1-4 or a view name, or type q to quit.")


def run_console(
    catalog_path: str | Path = DEFAULT_CATALOG,
    artifact_dir: str | Path = DEFAULT_ARTIFACT_DIR,
    *,
    embedding_model: str | None = None,
    top_k: int = TOP_K,
    input_fn: Callable[[str], str] = input,
    output_fn: Callable[[str], None] = print,
) -> None:
    if top_k < 1:
        raise ValueError("top_k must be positive")
    context = load_search_context(
        catalog_path,
        artifact_dir,
        embedding_model=embedding_model,
    )
    output_fn("Loaded the current Layer 2 product embedding index.")
    output_fn(f"Model: {context.model_id}")
    output_fn(f"Embedding dimension: {context.dimension}")
    output_fn("Type q to quit.")

    while True:
        selected_view = _choose_view(input_fn, output_fn)
        if selected_view is None:
            return
        while True:
            output_fn("Query:")
            try:
                query = input_fn("> ").strip()
            except (EOFError, KeyboardInterrupt):
                output_fn("")
                return
            command = query.casefold()
            if command == "q":
                return
            if command == "attribute":
                break
            if not query:
                output_fn("Enter a sentence, attribute, or q.")
                continue
            try:
                matches = search_view(
                    context,
                    selected_view,
                    query,
                    top_k=top_k,
                )
            except (RuntimeError, ValueError) as exc:
                output_fn(f"Semantic search failed: {exc}")
                continue
            print_results(context, selected_view, matches, output_fn=output_fn)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", default=str(DEFAULT_CATALOG))
    parser.add_argument("--artifact-dir", default=str(DEFAULT_ARTIFACT_DIR))
    parser.add_argument("--embedding-model")
    parser.add_argument("--top-k", type=int, default=TOP_K)
    args = parser.parse_args()
    if args.top_k < 1:
        parser.error("--top-k must be positive")
    try:
        run_console(
            args.catalog,
            args.artifact_dir,
            embedding_model=args.embedding_model,
            top_k=args.top_k,
        )
    except (ImportError, OSError, RuntimeError, TypeError, ValueError) as exc:
        parser.error(str(exc))


if __name__ == "__main__":
    main()
